### ISSUE TITLE
ISFC Slug to Bank Mapping is missing 

### ISSUE THREAD

**Issue by jaikathuria** [praveenpuglia/indian-banks#2]
One issue I faced while using this repo is that there is no mapping of ISFC slugs to the bank, on the basis of which the folder structure of assets is created.

So figuring out which asset to use for which bank took some time.

**Comment by jaikathuria** [comment]
Eventually ended up creating a mapping myself for all the assets 😄


Bank Name | Slug
-- | --
AU Small Finance Bank Limited | aubl
Bank of Baroda | barb
Bandhan Bank | bdbl
Bank of India | bkid
Central Bank Of India | cbin
City Union Bank | ciub
Canara Bank | cnrb
CSB Bank Limited | csbk
DCB Bank Limited | dcbl
Dhanalakshmi Bank | dlxb
Federal Bank | fdrl
HDFC Bank | hdfc
IDBI Bank | ibkl
ICICI Bank Limited | icic
IDFC First Bank Limited | idfb
Indian Bank | idib
Indusind Bank | indb
Indian Overseas Bank | ioba
Jammu and Kashmir Bank | jaka
Karnataka Bank Limited | karb
Kotak Mahindra Bank Limited | kkbk
Karur Vysya Bank | kvbl
Bank of Maharashtra | mahb
The Nainital Bank Limited | ntbl
Punjab and Sind Bank | psib
Punjab National Bank | punb
RBL Bank Limited | ratn
State Bank of India | sbin
South Indian Bank | sibl
Tamilnad Mercantile Bank Limited | tmbl
Union Bank of India | ubin
UCO Bank | ucba
Axis Bank | utib
Yes Bank | yesb

**Comment by praveenpuglia** [comment]
Send a PR?

**Comment by praveenpuglia** [comment]
I am gonna keep this table in readme. Closing this as well.
